### ISSUE TITLE
compile error at rui.c

### ISSUE THREAD

**Issue by letruongthanh3698** [RAKWireless/Products_practice_based_on_RUI#3]
..//Source/stm/service/rui/rui.c: In function 'rui_lora_get_status':
..//Source/stm/service/rui/rui.c:893:8: error: 'RUI_LORA_STATUS_T {aka struct RUI_LORA_STATUS}' has no member named 'EnableSleep'
  status->EnableSleep = g_lora_config.EnableSleep;

please check this issue

**Comment by RAKWireless** [comment]
Hi,
Please update the Application source code, and compile again. We just update the source code actually, and add that parameter in rui.h.
