### ISSUE TITLE
RAK4200 UART1 and UART2

### ISSUE THREAD

**Issue by KunYi** [RAKWireless/Products_practice_based_on_RUI#6]
Hello,
           Just want confirm UART1/UART2 function in RUI SDK
           from your documents can't get the information
           I guess the RUI configuration UART1 for AT command
           UART2 for user data(by user programming?)

**Comment by RAKWireless** [comment]
Hi @KunYi ,

In RUI SDK, UART1 which is the default UART which can be used for AT command and data transmition, for example, communicating with an external MCU.

UART2 is a reserve UART, which can be used for other things, for example, you can connect a GPS module with UART2.

**Comment by KunYi** [comment]
thank you,your reply very helpful
